name: newsproject_monolith
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  bloc: ^8.0.3
  build_runner: any
  cloud_firestore: ^3.1.15
  dio: ^4.0.6
  equatable: any
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed: any
  freezed_annotation: any
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: any
  json_serializable: any
  pretty_dio_logger: ^1.1.1
  rake:
    git:
      url: https://github.com/anu788/dart-rake.git
  webview_flutter: ^3.0.4

dev_dependencies:
  dart_code_metrics: ^4.15.2
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image_unavailable.png
