// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5YUhTRZlwczTH-aFjHKUcLTVQG5jwEs',
    appId: '1:721583865790:web:577b3b880212a2a08043ef',
    messagingSenderId: '721583865790',
    projectId: 'newsproject-3186c',
    authDomain: 'newsproject-3186c.firebaseapp.com',
    storageBucket: 'newsproject-3186c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Jp5etbHJq4t5vGII3tKVQqZSNhvhmg4',
    appId: '1:721583865790:android:f9795391da7c7deb8043ef',
    messagingSenderId: '721583865790',
    projectId: 'newsproject-3186c',
    storageBucket: 'newsproject-3186c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQljEr9hbL2hqHasDWnlkZvPBcn0czIDM',
    appId: '1:721583865790:ios:c28c24e60e73d35c8043ef',
    messagingSenderId: '721583865790',
    projectId: 'newsproject-3186c',
    storageBucket: 'newsproject-3186c.appspot.com',
    iosClientId: '721583865790-cmsmpeidadj8d3i2u3bmfh9nuagb59ok.apps.googleusercontent.com',
    iosBundleId: 'com.can.newsproject-monolith.dev',
  );
}
